# Generated by Django 4.2 on 2023-04-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='owner',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
